import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: dark,
        variables: {
          colorPrimary: "#FFA000",
          colorBackground: "#111114",
          colorForeground: "#f0f0f4",
          colorMutedForeground: "#c0c0cc",
          colorNeutral: "#808090",
          borderRadius: "0.5rem",
        },
        elements: {
          rootBox: "w-full max-w-[400px]",
          card: "w-full shadow-none bg-transparent",
          footerActionLink: "!text-[#FFA000] hover:!text-[#FFA000]/80",
          socialButtonsBlockButton:
            "!border-[#2a2a30] !bg-[#18181c] !text-[#f0f0f4] hover:!bg-[#1e1e23]",
          dividerLine: "!bg-[#2a2a30]",
          dividerText: "!text-[#808090]",
          formFieldLabel: "!text-[#c0c0cc]",
          formFieldInput:
            "!bg-[#18181c] !border-[#2a2a30] !text-[#f0f0f4] focus:!border-[#FFA000]",
          headerTitle: "!text-[#f0f0f4]",
          headerSubtitle: "!text-[#c0c0cc]",
        },
      }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
